file(GLOB BENCHMARK_CPP "${CMAKE_CURRENT_LIST_DIR}/bm_*.cpp")
foreach(benchfile ${BENCHMARK_CPP})
    get_filename_component(benchname ${benchfile} NAME_WE)
    string(REPLACE ".cpp" "" benchname ${benchname} )
    add_executable(${benchname} ${benchfile} )
    target_link_libraries(${benchname} benchmark)
    target_compile_options(${benchname} PUBLIC -Wall -Wextra -Werror)
    message(${benchfile})
endforeach(benchfile ${BENCHMARK_CPP})